### ISSUE TITLE
Support for all: syntax in embed patterns

### ISSUE THREAD

**Issue by Tatskaari** [please-build/go-rules#112]
re: https://github.com/thought-machine/please/issues/2806

https://pkg.go.dev/embed 
> If a pattern begins with the prefix ‘all:’, then the rule for walking directories is changed to include those files beginning with ‘.’ or ‘_’. For example, ‘all:image’ embeds both ‘image/.tempfile’ and ‘image/dir/.tempfile’.

We don't support this in the please_go tool

**Comment by peterebden** [comment]
It looks like this was added in 1.18 so it's not _just_ that I didn't read this properly upfront, we missed when it was added - although I think we were always slightly wrong about including the hidden files.
