### ISSUE TITLE
Invalid Go module version numbers in `go_mod_download` cause vulnerability scanner noise

### ISSUE THREAD

**Issue by chrisnovakovic** [please-build/go-rules#153]
`go_get`, `go_module` and now `go_repo` have always had the ability to refer to a particular version by any commit-ish in the Git source repo, for example:

```
go_module(
    name = "logrus",
    module = "github.com/sirupsen/logrus",
    version = "d40e25cd45ed9c6b2b66e6b97573a0413e4c23bd",  # This is actually v1.9.3
    # ...
)
```

The underlying `go_mod_download` target's modinfo is now derived from the value of `version`, and this value ultimately ends up in the [`runtime/debug.BuildInfo` struct](https://pkg.go.dev/runtime/debug#BuildInfo) embedded in the binary that Go outputs:

```
$ plz build //:gobinary
$ grep -aP '^dep\s+github.com/Sirupsen/logrus' $(plz query outputs //:gobinary)
dep     github.com/Sirupsen/logrus      d40e25cd45ed9c6b2b66e6b97573a0413e4c23bd
dep     github.com/Sirupsen/logrus      d40e25cd45ed9c6b2b66e6b97573a0413e4c23bd
```

The main consumers of this information - vulnerability scanners - unfortunately don't always know how to handle it, because the expectation is that the value of the third field in a `dep` entry abides by the [Go module version number spec](https://go.dev/doc/modules/version-numbers) - I can't find anything in the `runtime/debug` documentation that says this _has_ to be the case, but it's certainly the convention set by the standard Go toolchain. With some scanners (e.g. Trivy), failing to follow that convention results in warnings like this:

```
2023-08-21T17:11:53.151+0100    WARN    version error (d40e25cd45ed9c6b2b66e6b97573a0413e4c23bd): malformed version: d40e25cd45ed9c6b2b66e6b97573a0413e4c23bd
```

Some commercial scanners even assume that non-conformant values actually represent `v0.0.0`, and assume that the linked library is therefore affected by every vulnerability ever reported in that library, regardless of whether that's actually the case.

---

I suspect the cleanest way to deal with this would be to validate the version number in the `modinfo` target generated by `go_mod_download` - rather than just echoing `<module>@<version>` into the outputted modinfo file, a tiny Go tool could run `<version>` through [`golang.org/x/mod/module.Check`](https://pkg.go.dev/golang.org/x/mod/module#Check) and write the modinfo file itself if no error is returned or exit fatally if one is. We could either enforce that `version`s are Go module version numbers now and consider this a breaking change in go-rules, or we could gate it behind a feature flag and leave it disabled by default until v2.

**Comment by peterebden** [comment]
It seems reasonable to do the check - maybe in `please_go` if we can to avoid generating more Go binaries.

This will be a breaking change as you say - I think the best approach would be a config option that can be opted into until v2 where we make it compulsory.
