### ISSUE TITLE
go get ignores GOPROXY & GOPRIVATE

### ISSUE THREAD

**Issue by manfredlift** [please-build/go-rules#304]
It seems to to be hardcoded here https://github.com/please-build/go-rules/blob/c0ce501424168d8c58bb2a2a7087d1dd57e6a0cf/tools/please_go/goget/go_get.go#L30

This makes it unusable with private modules.

**Comment by toastwaffle** [comment]
Hi @manfredlift, thanks for flagging this! I've actually been working on setting up an internal Go module proxy internally, so I'll try to find some time to make this work next week :)

**Comment by toastwaffle** [comment]
Out of curiosity, would you be using your own module proxy server to get these private modules, or would you be relying on the `direct` mode for `GOPROXY`?

**Comment by toastwaffle** [comment]
Hey @manfredlift - how did you end up discovering this? Were you running the `please_go` tool directly?

I started writing a fix, but then noticed that `please_go get` doesn't seem to be used by any of the Go rules, and so it should possible be removed entirely (in favour of puku, which does a much better job). @Tatskaari wdyt?

**Comment by manfredlift** [comment]
@toastwaffle Hey, this was at the very beginning when I tried please. I thought this might be related but I got things compiling by passing GOPRIVATE & GOPROXY via `[BuildEnv]`

**Comment by toastwaffle** [comment]
Ok, cool. Having spoken to Jon I've filed #306 to remove `please_go get` entirely.
