### ISSUE TITLE
Support Go 1.18 modinfo

### ISSUE THREAD

**Issue by peterebden** [please-build/go-rules#45]
This seems to be becoming increasingly relied upon by the wider ecosystem. Currently plz binaries don't contain it and some things won't work with it.

It seems to be fairly simple; create a `debug.BuildInfo` and chuck it on a line in the importcfg prefixed with `modinfo`.
We don't have to fill everything in, but I suspect the module info will often be needed. I think we can get what we need there with `stamp` (assuming there is no dramatic downside to requesting to stamp every single `go_binary`)

**Comment by Tatskaari** [comment]
Unfortunately this doesn't seem to be well documented, and it's set at compile time so looking through the SDK doesn't really illuminate anything. 

Looks like we end up with an entry in the importcfg like this:
```
modinfo <some binary thing>
```

I assume that's a gob?
